### 1. Создание пользователя
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "test",
  "email": "test@example.com",
  "age": 33
}

### 2. Получить всех пользователей
GET http://localhost:8080/api/users

### 3. Получить пользователя по ID
GET http://localhost:8080/api/users/167

### 4. Обновить пользователя
PUT http://localhost:8080/api/users/167
Content-Type: application/json

{
  "name": "test1",
  "email": "test.updated@example.com",
  "age": 33
}

### 5. Удалить пользователя
DELETE http://localhost:8080/api/users/174

